version: "3.9"
services:
  postgres:
    image: "postgres:13-alpine"
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: money
        POSTGRES_USER: money
        POSTGRES_DB: my-money
        PGDATA: /var/lib/postgresql/data/pgdata